[package]
name = "pluckrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
itertools = "0.14.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
