[package]
name = "pluckrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
indexmap = { version = "2.10.0", features = ["serde"] }
itertools = "0.14.0"
regex = "1.11.1"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
